### ISSUE TITLE
using dynamic schemes: "this.getSelectedScheme(...).reset is not a function"

### ISSUE THREAD

**Issue by sillitoe** [greenify/msa-colorschemes#1]
Not sure whether this should be in 'msa' or 'msa-colorschemes'...

I'm trying to use my own dynamic colorscheme within 'msa'. I'm hitting the following error:

```
this.getSelectedScheme(...).reset is not a function
```

Code:

``` javascript
var m = new msa( opts );
m.g.colorscheme.addDynScheme( "dyn", function(letter, info) {
  return info.pos % 2 == 0 ? "#0f0" : "#fff";
});
m.g.colorscheme.set( "scheme", "dyn" );
m.seqs.reset( seqs );
```

However setting dynamic colorscheme _after_ `m.seqs.reset` works fine.

``` javascript
var m = new msa( opts );
m.g.colorscheme.addDynScheme( "dyn", function(letter, info) {
  return info.pos % 2 == 0 ? "#0f0" : "#fff";
});
m.seqs.reset( seqs );
m.g.colorscheme.set( "scheme", "dyn" );
```

Looks like the problem is down to msa.js (line:11732)

```
    return stat.on("reset", function() {
      if (this.getSelectedScheme().type === "dyn") {
        return this.getSelectedScheme().reset();
      }
```

Is this scheme reset necessary?

**Comment by wilzbach** [comment]
Yes this is a issue in the MSA (in [g/colorscheme.coffe](https://github.com/greenify/msa/blob/master/src/g/colorscheme.coffee))

https://github.com/greenify/msa/commit/4fb8384ce2f720301920e60e800c7ce3c948b152 should fix this issue :)

Working example @ jsbin:  http://jsbin.com/vamorexavi/1/edit?html,js,output

Thanks for letting me know!
